#!/bin/sh
rdlkf() { [ -L "$1" ] && (local lk="$(readlink "$1")"; local d="$(dirname "$1")"; cd "$d"; echo "$d/$(rdlkf "$lk")") || echo "$1"; }
DIR="$(dirname "$(rdlkf "$0")")"
/usr/bin/env node --harmony "$DIR/ng-annotate.js" "$@"
